[package]
name = "bot"
version = "0.1.0"
edition = "2021"

[dependencies]
serenity = "0.12"
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }
sqlx = { version = "0.6.0", features = ["mysql", "runtime-tokio-rustls"] }
dotenv = "0.15"
